export const ItemTypes = {
  MOVIE: "movie",
  TV: "tv",
};

export const DEFAULT_VIDEO_SOURCES = [
  {
    id: "1",
    name: "电影天堂",
    key: "innerSource",
    url: "http://caiji.dyttzyapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "2",
    name: "如意资源",
    key: "rycj",
    url: "https://cj.rycjapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "3",
    name: "暴风资源",
    key: "bfzy",
    url: "https://bfzyapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "4",
    name: "天涯资源",
    key: "tyyszy",
    url: "https://tyyszy.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "5",
    name: "小猫咪资源",
    key: "xiaomaomi",
    url: "https://zy.xmm.hk/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "6",
    name: "非凡影视",
    key: "ffzy",
    url: "http://ffzy5.tv/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "7",
    name: "黑木耳",
    key: "heimuer",
    url: "https://json.heimuer.xyz/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "8",
    name: "360资源",
    key: "zy360",
    url: "https://360zy.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "9",
    name: "iqiyi资源",
    key: "iqiyi",
    url: "https://www.iqiyizyapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "10",
    name: "卧龙资源",
    key: "wolong",
    url: "https://wolongzyw.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "11",
    name: "华为吧资源",
    key: "hwba",
    url: "https://cjhwba.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "12",
    name: "极速资源",
    key: "jisu",
    url: "https://jszyapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "13",
    name: "豆瓣资源",
    key: "dbzy",
    url: "https://dbzy.tv/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "14",
    name: "魔爪资源",
    key: "mozhua",
    url: "https://mozhuazy.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "15",
    name: "魔都资源",
    key: "mdzy",
    url: "https://www.mdzyapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "16",
    name: "最大资源",
    key: "zuid",
    url: "https://api.zuidapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "17",
    name: "樱花资源",
    key: "yinghua",
    url: "https://m3u8.apiyhzy.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "18",
    name: "百度云资源",
    key: "baidu",
    url: "https://api.apibdzy.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "19",
    name: "无尽资源",
    key: "wujin",
    url: "https://api.wujinapi.me/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "20",
    name: "旺旺短剧",
    key: "wwzy",
    url: "https://wwzy.tv/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "21",
    name: "iKun资源",
    key: "ikun",
    url: "https://ikunzyapi.com/api.php/provide/vod",
    enabled: true,
    type: "video",
  },
  {
    id: "22",
    name: "量子资源站",
    key: "lzi",
    url: "https://cj.lziapi.com/api.php/provide/vod/",
    enabled: true,
    type: "video",
  },
];

export const DEFAULT_DANMAKU_SOURCES = [];
